[project]
name = "firstcash.py"
description = "A basic Python library to communicate with FirstCash' mobile app API."
authors = [
    {name = "AgentLoneStar007", email = "contactagent.3gxdf@simplelogin.com"}
]
requires-python = ">3.9"  # TODO: Verify this will work in Python 3.9 and above
license = {file = "LICENSE"}
dependencies = [
    "requests"
]

[project.urls]
Documentation = "https://github.com/AgentLoneStar007/FirstCash.Py/tree/main/docs"
"Issues" = "https://github.com/AgentLoneStar007/FirstCash.Py/issues"